"use client";
import { useLanguage } from "./LanguageProvider";
export function PilotGuide() {
  const { t, language } = useLanguage();
  return <section id="pilot-help" lang={language} aria-label={t("Pilot help")} className="mt-8 rounded-xl border border-line bg-surface p-6 text-sm">
    <h2 className="font-display text-xl">{t("Getting started & common questions")}</h2>
    <p className="mt-2 text-ink/70">{t("Family and friends pilot: please use fictional details while we improve the app.")}</p>
    <div className="mt-4 space-y-4">
      <details><summary className="cursor-pointer font-medium">{t("How do I fix a transcript mistake?")}</summary><p className="mt-2">{t("Open the conversation, then Fix a transcript mistake below the summary. Choose Correct transcript, edit the words, and Save correction. The original stays available. Saving uses no AI requests. Preview updated notes uses one AI request, even if it fails. Suggestions stay separate: use Edit on existing tasks or decisions to make changes. The preview does not update your summary or drafts.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("Can I undo a client merge?")}</summary><p className="mt-2">{t("Open Clients, then Recent merges & undo. Find the merge, choose Undo merge, and confirm. This restores the original clients and conversation links without using AI requests. If records changed afterward, undo stops to protect newer work. Older merges may need manual recovery review. Similar names alone do not mean two clients should be combined.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("What if a name is spelled differently in my recording?")}</summary><p className="mt-2">{t("You can say names naturally. Select the intended client before recording to keep the conversation attached to them. In the conversation's People section, use Confirm this person to choose an existing client for a detected name. The original extracted name stays visible. This does not rewrite the transcript, summary, tasks or saved drafts, or change the conversation's main client. Review names before sharing a draft.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("Can I save an email or text draft for later?")}</summary><p className="mt-2">{t("Yes. Open a conversation and choose Draft email or text below the summary. After reviewing or editing your message, click Save draft. Each conversation keeps one email and one text draft for your account. Saving again replaces that format's previous version. Saved drafts reopen when you return; unsaved edits may be lost when you leave. Saving and reopening do not use AI requests. Copying a draft does not send it or complete a task. Deleting the conversation also removes its saved drafts.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("What do I do after signing in?")}</summary><ol className="mt-2 list-decimal space-y-2 pl-5"><li>{t("Open Conversations. Select an existing client, add a new client by name, or choose Assign later. Then record a short voice note or upload audio.")}</li><li>{t("Preview your recording, then submit it. Wait for your notes to be ready.")}</li><li>{t("Open the conversation. Compare the transcript and summary with what you said; edit decisions and tasks where needed.")}</li><li>{t("Check the linked client. Use the dashboard to follow up and mark finished tasks complete.")}</li></ol></details>
      <details><summary className="cursor-pointer font-medium">{t("Can I organize recordings by person or category?")}</summary><p className="mt-2">{t("Use Clients to find a person and see their linked conversations. Your chosen client stays assigned even if a name is transcribed differently. Assign later keeps the recording unassigned. Older recordings may have automatic matches; check those when names are similar. On a conversation, unlink an incorrect match, then search for the right existing client by name. Each recording has one client link. Custom folders and tags are not available yet. Conversation search currently searches titles and filenames, not transcript contents.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("What are the pilot recording and storage limits?")}</summary><p className="mt-2">{t("The in-app recorder stops after three minutes. Uploads can be up to 100 MB per file, but processing providers may impose a smaller limit. For testing, use short fictional recordings. When pilot allowances are enabled, the allowance panel shows your remaining recordings, storage and daily usage. The pilot allowance is 30 saved recordings, 250 MiB of audio, and five new recordings per day, each up to three minutes. These limits do not promise permanent retention. Keep your own copy of anything important.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("Are there limits on AI client reviews?")}</summary><p className="mt-2">{t("A client review supports up to 50 transcribed conversations and 100 open tasks, with an additional text-size limit. Long histories may reach that limit sooner. Generate or refresh a review when you need it; refreshing uses AI processing. When pilot allowances are enabled, client reviews, dashboard briefings and follow-up drafts share five AI requests per day. Requests count once AI processing starts, including unsuccessful or outdated results. You can still read saved notes at the limit. Two user-requested processing retries are allowed per day. If information changes while a review is being generated, refresh the page and try again.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("Who can access my conversations?")}</summary><p className="mt-2">{t("Your signed-in account can access its own records; other ordinary users are blocked from viewing or changing them. The service and its processing providers handle audio and text to produce your results. This is not end-to-end encrypted messaging, and account separation is not a promise that nobody operating the service can access data. Use fictional information during this pilot and only submit recordings you have permission to share.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("What happens when I delete a recording?")}</summary><p className="mt-2">{t("Delete on the Conversations list removes that recording and its associated conversation results from the active app. The client and their other recordings remain. There is no undo in the app. Backup copies may remain until their retention period expires; deletion is not a promise of immediate removal from every backup or provider system. Contact Robert with questions about removing your pilot data.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("How accurate are the notes and suggested actions?")}</summary><p className="mt-2">{t("We do not yet have a measured accuracy percentage. Pilot checks compare fictional recordings with their transcripts, summaries, names, amounts, dates, owners and tasks. Check for both missing details and invented claims. A suggested action should reflect what was actually agreed, not a new obligation invented by AI. You can correct decisions and tasks while keeping the original AI text. Saved client reviews include source quotes; verify their meaning before confirming a task is complete.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("I completed a task by accident. Can I bring it back?")}</summary><p className="mt-2">{t("Yes. Completing a task does not delete it; it moves out of the default Open view. Open its conversation and, under Tasks to review, change Show tasks to Completed or All tasks. Find the task and choose Reopen. For recently completed tasks, you can also open Activity & completed tasks on the dashboard and choose Reopen.")}</p></details>
      <details><summary className="cursor-pointer font-medium">{t("How can I give useful feedback?")}</summary><p className="mt-2">{t("Tell Robert what you tried, what you expected, and what happened. For a fictional recording, include the incorrect wording and the correct version. Also say which dashboard section helped you decide what to do next, and what was missing. Please leave personal or confidential details out of screenshots.")}</p></details>
    </div>
  </section>;
}

export function PilotHelpLink() {
  const { t } = useLanguage();
  return <a href="#pilot-help" className="mb-4 block text-sm text-accent underline">{t("Help: getting started, privacy & limits")}</a>;
}
