export function PilotGuide() {
  return <section id="pilot-help" aria-label="Pilot help" className="mt-8 rounded-xl border border-line bg-surface p-6 text-sm">
    <h2 className="font-display text-xl">Getting started & common questions</h2>
    <p className="mt-2 text-ink/70">Family and friends pilot: please use fictional details while we improve the app.</p>
    <div className="mt-4 space-y-4">
      <details><summary className="cursor-pointer font-medium">What do I do after signing in?</summary><ol className="mt-2 list-decimal space-y-2 pl-5"><li>Open Conversations. Select an existing client, add a new client by name, or choose Assign later. Then record a short voice note or upload audio.</li><li>Preview your recording, then submit it. Wait for your notes to be ready.</li><li>Open the conversation. Compare the transcript and summary with what you said; edit decisions and tasks where needed.</li><li>Check the linked client. Use the dashboard to follow up and mark finished tasks complete.</li></ol></details>
      <details><summary className="cursor-pointer font-medium">Can I organize recordings by person or category?</summary><p className="mt-2">Use Clients to find a person and see their linked conversations. Your chosen client stays assigned even if a name is transcribed differently. Assign later keeps the recording unassigned. Older recordings may have automatic matches; check those when names are similar. On a conversation, unlink an incorrect match, then search for the right existing client by name. Each recording has one client link. Custom folders and tags are not available yet. Conversation search currently searches titles and filenames, not transcript contents.</p></details>
      <details><summary className="cursor-pointer font-medium">What are the pilot recording and storage limits?</summary><p className="mt-2">The in-app recorder stops after three minutes. Uploads can be up to 100 MB per file, but processing providers may impose a smaller limit. For testing, use short fictional recordings. There is no published allowance for recordings per account or total storage yet; this does not mean unlimited storage or permanent retention. Keep your own copy of anything important.</p></details>
      <details><summary className="cursor-pointer font-medium">Are there limits on AI client reviews?</summary><p className="mt-2">A client review supports up to 50 transcribed conversations and 100 open tasks, with an additional text-size limit. Long histories may reach that limit sooner. Generate or refresh a review when you need it; refreshing uses AI processing. The pilot does not promise unlimited AI use. If information changes while a review is being generated, refresh the page and try again.</p></details>
      <details><summary className="cursor-pointer font-medium">Who can access my conversations?</summary><p className="mt-2">Your signed-in account can access its own records; other ordinary users are blocked from viewing or changing them. The service and its processing providers handle audio and text to produce your results. This is not end-to-end encrypted messaging, and account separation is not a promise that nobody operating the service can access data. Use fictional information during this pilot and only submit recordings you have permission to share.</p></details>
      <details><summary className="cursor-pointer font-medium">What happens when I delete a recording?</summary><p className="mt-2">Delete on the Conversations list removes that recording and its associated conversation results from the active app. The client and their other recordings remain. There is no undo in the app. Backup copies may remain until their retention period expires; deletion is not a promise of immediate removal from every backup or provider system. Contact Robert with questions about removing your pilot data.</p></details>
      <details><summary className="cursor-pointer font-medium">How accurate are the notes and suggested actions?</summary><p className="mt-2">We do not yet have a measured accuracy percentage. Pilot checks compare fictional recordings with their transcripts, summaries, names, amounts, dates, owners and tasks. Check for both missing details and invented claims. A suggested action should reflect what was actually agreed, not a new obligation invented by AI. You can correct decisions and tasks while keeping the original AI text. Saved client reviews include source quotes; verify their meaning before confirming a task is complete.</p></details>
      <details><summary className="cursor-pointer font-medium">How can I give useful feedback?</summary><p className="mt-2">Tell Robert what you tried, what you expected, and what happened. For a fictional recording, include the incorrect wording and the correct version. Also say which dashboard section helped you decide what to do next, and what was missing. Please leave personal or confidential details out of screenshots.</p></details>
    </div>
  </section>;
}
